version: '3.7'

services:
    database_ng:
      image: postgres
      container_name: database_ng
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=ngcash
        - POSTGRES_DB=ng
      volumes:
        - pgdata:/data/postgres
      
    app:
      build: .
      container_name: ng
      restart: always
      ports:
        - 3333:3333
      volumes:
        - .:/usr/app
      links: 
        - database_ng
      depends_on:
        - database_ng

volumes:
  pgdata:
    driver: local